# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

language: generic # optional, just removes the language badge

services:
  - docker

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
  matrix: # each line is a job
    - ROS_DISTRO="melodic"
      BEFORE_INSTALL_TARGET_DEPENDENCIES='
        apt-get remove -y -qq pybind11-dev python-pybind11 python3-pybind11
        && apt-get install -y -qq python3-pip python3-joblib python3-pytest
        && mkdir $HOME/src && cd $HOME/src
        && git clone https://github.com/pybind/pybind11.git -b v2.5
        && mkdir -p pybind11/build
        && cd pybind11/build
        && cmake ..
        && make && make install
        '
      UPSTREAM_WORKSPACE=file
      
 
# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

script:
  - .industrial_ci/travis.sh
